"""empty message

Revision ID: 2cdfb9eb557b
Revises: 909f57eef359
Create Date: 2022-05-19 18:56:51.262264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdfb9eb557b'
down_revision = '909f57eef359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hood', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hood')
    # ### end Alembic commands ###
