"""empty message

Revision ID: 73a282860a7a
Revises: 67fe78589c93
Create Date: 2022-05-18 17:18:48.490612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a282860a7a'
down_revision = '67fe78589c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hoods', sa.Column('hood_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hoods', 'hood_pic')
    # ### end Alembic commands ###
